/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/demo/evidence-report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Demo Evidence Report
         * @description Return a deterministic synthetic report without model or RPC dependencies.
         */
        get: operations["demo_evidence_report_v1_demo_evidence_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CodeFinding */
        CodeFinding: {
            /** Scan Id */
            scan_id: string;
            /** Finding Id */
            finding_id: string;
            /** Rule Id */
            rule_id: string;
            severity: components["schemas"]["Severity"];
            status: components["schemas"]["FindingStatus"];
            /** Title */
            title: string;
            /** Source Hash */
            source_hash: string;
            code_location: components["schemas"]["CodeLocation"];
            /** Deterministic Evidence */
            deterministic_evidence?: string[];
            /** Tool Versions */
            tool_versions?: {
                [key: string]: string;
            };
            /**
             * Is Synthetic
             * @default true
             */
            is_synthetic: boolean;
        };
        /** CodeLocation */
        CodeLocation: {
            /** File */
            file: string;
            /** Start Line */
            start_line: number;
            /** End Line */
            end_line: number;
            /** Excerpt */
            excerpt: string;
        };
        /** ControlSpec */
        ControlSpec: {
            /** Asset Id */
            asset_id: string;
            /** Document Id */
            document_id: string;
            /** Constraint Id */
            constraint_id: string;
            /** Field */
            field: string;
            /** Value */
            value: string | number | boolean;
            /** Unit */
            unit?: string | null;
            evidence_span: components["schemas"]["EvidenceSpan"];
            /**
             * Confirmed
             * @default false
             */
            confirmed: boolean;
            /**
             * Is Synthetic
             * @default true
             */
            is_synthetic: boolean;
        };
        /**
         * EvidenceMode
         * @enum {string}
         */
        EvidenceMode: "LIVE" | "REPLAY";
        /** EvidenceReport */
        EvidenceReport: {
            /** Report Id */
            report_id: string;
            scan_run: components["schemas"]["ScanRun"];
            /** Controls */
            controls: components["schemas"]["ControlSpec"][];
            /** Code Findings */
            code_findings: components["schemas"]["CodeFinding"][];
            /** Mismatches */
            mismatches: components["schemas"]["MismatchFinding"][];
            /** Onchain Evidence */
            onchain_evidence: components["schemas"]["OnchainEvidence"][];
            /** Lineage */
            lineage: {
                [key: string]: unknown;
            };
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
            /**
             * Is Synthetic
             * @default true
             */
            is_synthetic: boolean;
        };
        /** EvidenceSpan */
        EvidenceSpan: {
            /** Document Id */
            document_id: string;
            /** Page */
            page: number;
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Quote */
            quote: string;
        };
        /**
         * FindingStatus
         * @enum {string}
         */
        FindingStatus: "CONFIRMED" | "PROBABLE" | "NEEDS_REVIEW" | "UNKNOWN";
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /**
             * Service
             * @constant
             */
            service: "rwa-guard-api";
            /** P0 Ready */
            p0_ready: boolean;
            /**
             * P1 Chain
             * @enum {string}
             */
            p1_chain: "configured" | "disabled";
        };
        /**
         * ImplementationStatus
         * @enum {string}
         */
        ImplementationStatus: "IMPLEMENTED" | "PARTIAL" | "MISSING" | "UNKNOWN";
        /** MismatchFinding */
        MismatchFinding: {
            /** Mismatch Id */
            mismatch_id: string;
            /** Constraint Id */
            constraint_id: string;
            /** Finding Id */
            finding_id: string;
            implementation_status: components["schemas"]["ImplementationStatus"];
            severity: components["schemas"]["Severity"];
            /** Evidence Links */
            evidence_links: string[];
            /**
             * Is Synthetic
             * @default true
             */
            is_synthetic: boolean;
        };
        /** OnchainEvidence */
        OnchainEvidence: {
            /** Asset Id */
            asset_id: string;
            mode: components["schemas"]["EvidenceMode"];
            /** Chain Id */
            chain_id: number;
            /** Tx Hash */
            tx_hash: string;
            /** Log Index */
            log_index: number;
            /** Block Number */
            block_number: number;
            /** Event Name */
            event_name: string;
            /** Previous Value */
            previous_value?: string | null;
            /** Changed Value */
            changed_value?: string | null;
            /** Fixture Version */
            fixture_version?: string | null;
            /**
             * Is Synthetic
             * @default true
             */
            is_synthetic: boolean;
        };
        /** ScanRun */
        ScanRun: {
            /** Scan Id */
            scan_id: string;
            /** Asset Id */
            asset_id: string;
            status: components["schemas"]["ScanStatus"];
            /** Input Hashes */
            input_hashes: {
                [key: string]: string;
            };
            /** Rule Versions */
            rule_versions: {
                [key: string]: string;
            };
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Completed At */
            completed_at?: string | null;
            /**
             * Is Synthetic
             * @default true
             */
            is_synthetic: boolean;
        };
        /**
         * ScanStatus
         * @enum {string}
         */
        ScanStatus: "QUEUED" | "RUNNING" | "COMPLETED" | "PARTIAL" | "FAILED";
        /**
         * Severity
         * @enum {string}
         */
        Severity: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW" | "INFO";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    demo_evidence_report_v1_demo_evidence_report_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceReport"];
                };
            };
        };
    };
}
